export const nationalities = [
    { value: "", label: "Select Nationality" },
    { value: "uae", label: "United Arab Emirates" },
    { value: "saudi", label: "Saudi Arabia" },
    { value: "egypt", label: "Egypt" },
    { value: "qatar", label: "Qatar" },
    { value: "kuwait", label: "Kuwait" },
    { value: "bahrain", label: "Bahrain" },
    { value: "oman", label: "Oman" },
    { value: "jordan", label: "Jordan" },
    { value: "lebanon", label: "Lebanon" },
    { value: "morocco", label: "Morocco" },
    { value: "algeria", label: "Algeria" },
    { value: "tunisia", label: "Tunisia" },
    { value: "sudan", label: "Sudan" },
    { value: "libya", label: "Libya" },
    { value: "mauritania", label: "Mauritania" },
    { value: "somalia", label: "Somalia" },
    { value: "comoros", label: "Comoros" },
    { value: "djibouti", label: "Djibouti" },
    { value: "palestine", label: "Palestine" },
    { value: "syria", label: "Syria" },
    { value: "iraq", label: "Iraq" },
    { value: "yemen", label: "Yemen" },
    { value: "usa", label: "United States" },
    { value: "france", label: "France" },
    { value: "germany", label: "Germany" },
  ];
  